name: axpertflutter
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.1.1+2101


environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_splash_screen: ^1.3.0
  animated_icon: ^0.0.5
  back_button_interceptor: ^7.0.0
  build_runner: ^2.4.6
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  connectivity_plus: ^5.0.1
#  device_info_plus: ^9.1.0
  firebase_auth: ^4.9.0
  firebase_core: ^2.15.1
  firebase_messaging: ^14.7.1
  flutter_easyloading: ^3.0.5
  flutter_inappwebview: ^5.8.0
  flutter_launcher_icons: ^0.13.1
  flutter_local_notifications: ^16.1.0
  flutter_spinkit: ^5.2.0
  flutter_staggered_animations: ^1.1.1
  font_awesome_flutter: ^10.5.0
  get: ^4.6.6
  get_storage: ^2.1.1
  google_fonts: ^6.1.0
  google_sign_in: ^6.1.5
  json_serializable: ^6.7.1
  hexcolor: ^3.0.1
  http: ^1.1.0
  image_picker: ^1.0.4
  loading_overlay: ^0.3.0
  otp_text_field: ^1.1.3
  package_info_plus: ^4.2.0
  permission_handler: ^11.0.1
  platform_device_id: ^1.0.1
  qr_code_scanner: ^1.0.1
  scan: ^1.6.0
  scrollable_positioned_list: ^0.3.8
  syncfusion_flutter_calendar: ^23.1.41
  syncfusion_flutter_charts: ^23.1.41
  text_scroll: ^0.2.0
  background_location: ^0.11.8


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/agilelabslogo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
#  web:
#    generate: true
#    image_path: "images/agilelabslogo.png"
#    background_color: "#hexcode"
#    theme_color: "#hexcode"


  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/lang/
    - assets/images/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf

    - family: Gellix
      fonts:
        - asset: assets/fonts/Gellix-Black.ttf


#        - asset: assets/fonts/Poppins-Medium.ttf


  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
